### ISSUE TITLE
IOS connect fail callback error

### ISSUE THREAD

**Issue by batman11111** [don/cordova-plugin-rfduino#20]
I'm using cordova to install your latest rfduino plugin (0.1.2 I believe it is)for IOS.  When the rfduino.connect funtion is called it always fires a fail callback as well as a success callback.  So when I connect to a rfduino it connects but also fires the fail callback.  I've used the plugin on android with phonegap build and have not had the problem.  Seems to be only with IOS (7.12 havent tried other versions) using cordova.  Let me know if I'm doing something wrong or if you need more info.  thanks.

**Comment by don** [comment]
What version of Cordova are you running?  Let me know what you get from `cordova -v` and `cordova platform ls`

**Comment by batman11111** [comment]
Cordova version is 4.1.2
Installed platforms: ios 3.7.0 (Available platforms: amazon-fireos, android, blackberry10, browser, firefoxos)

**Comment by don** [comment]
I've seen a similar problem in the past. I haven't had time to look into it. I downgraded to Cordova 4.0.0 with iOS 3.7.0 and things are working OK. I'll take a look at the newer version to see if I can duplicate / fix the issue.  Until then, you can downgrade with `npm install -g cordova@4.0.0`

You'll probably need to remove and add the iOS platform to get things working.

**Comment by batman11111** [comment]
Great. Thanks for the info.

Sent from Yahoo Mail on Android

**Comment by don** [comment]
This is a bug in Cordova https://issues.apache.org/jira/browse/CB-8063

**Comment by batman11111** [comment]
Thanks for the info. I downgraded like you suggested and everything is working fine. Great plugin by the way. 

Sent from Yahoo Mail on Android

**Comment by don** [comment]
Glad it's working. I'll update this code in a bit so it will work with the newer Cordova. The bug is being fixed for a future release of Cordova. I'll close this issue when things are updated.
